### ISSUE TITLE
Incorrect dead stones

### ISSUE THREAD

**Issue by Marsgoat** [SabakiHQ/deadstones#4]
![image](https://user-images.githubusercontent.com/48231313/160743622-3761d925-bfd2-426a-9109-2eee0bc2e245.png)

**Comment by yishn** [comment]
This module does not provide a 100% accurate estimation.

**Comment by changjiuxiong** [comment]
> This module does not provide a 100% accurate estimation.

对于单眼死棋，结果总是100%错误。playTillEnd方法判断敌人的单眼位置是禁入点，导致单眼死棋从来不会被提吃，进而导致无法识别单眼死棋。无论iterations多大都是这样。
